### ISSUE TITLE
Animate once

### ISSUE THREAD

**Issue by upq** [dbramwell/react-animate-on-scroll#1]
The animation is triggered once the item in view perfectly and when its out of view it disappears,
Scrolling up brings that back again.

I have modified it by adding an 2 more boolean attributes 
```animateOnce```
```isAnimationFinished```

if you want to implement that functionality I can PR

thanks

**Comment by dbramwell** [comment]
Hey, sounds like a good idea to me. Create the pull request and I'll have a look

**Comment by upq** [comment]
Sure, I will propose one once I finish working on the porject at hand now.

**Comment by supra28** [comment]
@upq Can you guide me or perhaps create a gist showing how you did this?

**Comment by dbramwell** [comment]
I think you should get something working doing the following:

When the element becomes partially visible [here](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L55), set a boolean in the state "hasAnimated" or similar to true.

Then in the getStyle function, when checking if the element should be hidden in lines [92](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L92) and [94](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L94) add an extra check for "!(hasAnimated && animateOnce)".

You'd need to do a similar check in the getClasses function too I think, to stop the animation from triggering again.

**Comment by hawkins** [comment]
Hey all, I implemented @dbramwell 's suggestions and sent in a PR since no one else has yet. Find it at #3, but the commit with instructions that I think you all might appreciate to implement in your own forks if need-be can be found here: https://github.com/dbramwell/react-animate-on-scroll/pull/3/commits/1464794c1568e38550f09ff700bb942e111b4aef

cc @supra28
