### ISSUE TITLE
onComplete fires too early

### ISSUE THREAD

**Issue by sensationmm** [dbramwell/react-animate-on-scroll#13]
Great plugin, callback works great when the component slides into view normally, however it seems to be triggered by the component entering the viewport rather than when the animation has actually finished

It looks like this condition  on line 97 allows it to fire when not completely visible
`return visible.partially && !visible.completely`

In the example, if you scroll down slowly the alert fires as the component enters the viewport - see screenshot

![image](https://user-images.githubusercontent.com/8363839/33263315-462bc802-d361-11e7-955b-d0dd27277e16.png)

**Comment by dbramwell** [comment]
Thanks. Yeah, you're right. I'll try again in a bit. After I pushed I realised we probably also want different callbacks for animatein and animateout?

**Comment by dbramwell** [comment]
Ok, made some changes, we now have 'afterAnimatedIn' and 'afterAnimatedOut'. The docs/demo have more info. Let me know if you have any more issues. If it seems fine, please close.

**Comment by sensationmm** [comment]
Works great! Thanks for the quick resolution :)
