### ISSUE TITLE
Scroll animations not working in IE.

### ISSUE THREAD

**Issue by sumanth17** [dbramwell/react-animate-on-scroll#14]
I have tried implementing this library in my project and facing issues with internet explorer. I looked at the code and it is using scrollY which is not supported by i.e . Can you please take a look at it and update scrollY to pageYOffset as it is better for cross browser compatibility.

I have modified it from scrollY to pageYOffset

if you want to implement this I can give PR

Thanks

**Comment by dbramwell** [comment]
Hey, thanks for the heads up. I've implemented the change you suggested and it seems to be working in IE now. The [demo](https://dbramwell.github.io/react-animate-on-scroll/#home) page has some other issue in IE that breaks the way the code is displayed, but the animations work successfully.
