### ISSUE TITLE
Animations aren't coming in when programatically scrolling

### ISSUE THREAD

**Issue by franszo** [dbramwell/react-animate-on-scroll#20]
hi there, hope theres still some support for this! When Im using any programatical approach to scroll, fore example `window.scrollTo( 0, 0 );` , none of the animations are triggered, I need to touch to scroll to trigger the animations, I guess wrong event listener?

Could you please have a look?

thanks!

**Comment by dbramwell** [comment]
Hi
It is still supported when I get chance. I've been refactoring it a fair bit over the the last few weeks as I started discovering more and more edge cases that didn't work as expected. I've published the new version (2.0.0) today, would you mind testing with that if you get chance?

That said, I don't expect the new version to fix your issue. `window.scrollTo(x,y)` should work, it is in fact the same method the automated tests use.

If you use `window.scrollTo(x,y)` to scroll an element into the viewport then animateIn should be triggered, however if you use it to scroll past an element then the animation might not be triggered as the scroll listener is throttled to only be called every 50 milliseconds.

So, are you scrolling to the element or past the element?

**Comment by franszo** [comment]
Many thanks @dbramwell will have a try and I'll come back asap!

**Comment by franszo** [comment]
not sure what, maybe it was my fault, bot works like a charm now, also with 2.0 seems to be better! Thanks for this new release ;)
