### ISSUE TITLE
I live in a van and work on a hacked chromebook so can't test in IE

### ISSUE THREAD

**Issue by dbramwell** [dbramwell/react-animate-on-scroll#22]
I recently released version 2.0.0 which seems to work on mobile chrome, a few versions of desktop chrome and firefox, but I am unable to test in IE currently. If anyone reads this and can confirm whether or not the animations on the [demo page](https://dbramwell.github.io/react-animate-on-scroll/#home) work correctly in IE I'd be very appreciative.

The code samples on the demo page used to display incorrectly but the animations worked. Hopefully the current state is the same or better.

**Comment by hawkins** [comment]
Just read your story in another issue comment, wow! I'm happy to help however I can with the library, so I just checked this on IE right quick. Not trying to steal @Code47x's thunder if he wants this task (fine by me!! 👍 ), but there's one interesting thing about the IE demo page...

In IE, the demo source appears babelified, unlike in chrome:

![image](https://user-images.githubusercontent.com/9123458/36636717-f921e062-1999-11e8-8014-c4528420a83f.png)

**Comment by dbramwell** [comment]
Thanks for this. As long as the animations still work i'm happy for now.

The code displaying incorrectly has been an issue since IE was first brought to my attention. I believe it originates in [jsx-to-string](https://github.com/grommet/jsx-to-string) but haven't had chance to investigate. Maybe some sort of alert should be added if someone opens it in IE?

**Comment by michellomp** [comment]
Hi @dbramwell I've tested the demo page in IE 11 and for the first animation there's a scrollbar appearing in the bottom and then disappear when the animation is finished
<img width="810" alt="reactanime" src="https://user-images.githubusercontent.com/13666439/37491648-d67130e0-289e-11e8-9b51-01d631d63e76.png">
It only happen when the zoom is above 100%

**Comment by dbramwell** [comment]
Hey, thanks.

I assume it's because of that specific animation causing the element to appear momentarily off screen to the right. It's probably possible to set overflow-x to hidden or something in the CSS of the page, to stop the scrollbar appearing. I'll have a look when I get chance

**Comment by thebarty** [comment]
If you have parallels, those virtual images might work https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by dbramwell** [comment]
They're a good idea. Unfortunately the Chromebook has a 16gb harddrive (and keeps destroying memory sticks) so I don't have the space for the images.

I'm no longer in the van, now back in London looking for work. I am however stuck with the Chromebook until I get a job and get paid.
