### ISSUE TITLE
Animating once not working anymore in V2

### ISSUE THREAD

**Issue by franszo** [dbramwell/react-animate-on-scroll#23]
animateOnce="true" not working anymore in V2, instead always animating

**Comment by gf5901** [comment]
Same for me

**Comment by Code47X** [comment]
Same problem.

**Comment by ldevalbray** [comment]
Same here !

**Comment by hawkins** [comment]
Hey all, I wrote this feature originally so I’ll try to take a look at this today

**Comment by hawkins** [comment]
Turns out `animateOnce` isn't even checked anymore in the code; I'll send in a PR later today to correct this

**Comment by Code47X** [comment]
@hawkins  Much appreciated! Thanks!

**Comment by dbramwell** [comment]
Sorry guys, especially @hawkins. Seems a dodgy test case and poor observation of the demo page on my part caused me to miss this.

I saw the issue reported the other day and created a fix but haven't had good enough internet yet to be able to release a new version. I should be able to upload it later today in 6 hours or so.

**Comment by hawkins** [comment]
No problem for me, glad you found the root cause so we can prevent it in the future :) I’ll wait for you to upload your fix then! 

Thanks a bunch, @dbramwel.

**Comment by Code47X** [comment]
@dbramwell Just wanted to say great work on this component. Hoping I can contribute sometime if I see a way.

**Comment by hawkins** [comment]
@Code47X ditto, it's a great help! If you're looking for contribution opportunities, there's always #22 if you have Windows, and #24 if you like CSS :)

**Comment by dbramwell** [comment]
Thanks guys. Uploaded the fix, leaving "animating" set to true [if animateOnce is set](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L121)

Sorry again, seems people like this feature. I'll be more mindful of it in future :)
