### ISSUE TITLE
Inline display

### ISSUE THREAD

**Issue by gf5901** [dbramwell/react-animate-on-scroll#24]
It would be nice if we could specify if it is inline or not. 
Right now the main element is a `<div>`... so it is always `display: block`.
I might just create a PR later if I feel less lazy later.

**Comment by hawkins** [comment]
For what it's worth, I reckon you could play with `ref` and do this yourself

**Comment by dbramwell** [comment]
Hey, thanks for the input. You have a very valid point.

I think good features would be the options to pass a style object and possible classes to the div, that'd give more flexibility compared to just being able to pass in some sort of display prop.

If you get chance a PR would be good. Or if you could comment on the existing PR that's looking into this.

**Comment by dbramwell** [comment]
This can now be achieved in version 2.0.2 by using the style prop, thanks @Code47X.
