### ISSUE TITLE
Animations not working well on phones

### ISSUE THREAD

**Issue by ldevalbray** [dbramwell/react-animate-on-scroll#25]
Hello,
First of all, thank you for this nice component !
However, sometimes, animations are a bit laggy on phones. It would be great to have a props where you could specify a break point (ex : 1024) where the animations would not load.
Or maybe a boolean like (animateOnPhone = {false})
Thank you !

**Comment by hawkins** [comment]
Are you trying with version 2.0? Looks like #21 addressed mobile support

**Comment by ldevalbray** [comment]
ok thank you ! Now I have the #23 issue though ;)

**Comment by hawkins** [comment]
Good to hear, and FYI a fix for #23 is on its way to be shipped tonight :)

@dbramwell , can we close this?

**Comment by dbramwell** [comment]
@hawkins yeah I think so.

@ldevalbray if you still have mobile issues please reopen, or open another one and let me know.

Thanks a lot
