### ISSUE TITLE
have item stick around after having faded in

### ISSUE THREAD

**Issue by tansaku** [dbramwell/react-animate-on-scroll#38]
Great project - we were just using the simple example for fadein, is there a way to have an item stick around after it has faded in once, i.e. not have it disappear once we scroll away from it again?

**Comment by dbramwell** [comment]
Thanks for the kind words. If you set animateOnce to true then I think it should give you the desired result. There's an example on the demo page:
https://dbramwell.github.io/react-animate-on-scroll/#animateOnce
