### ISSUE TITLE
Not work on any component 

### ISSUE THREAD

**Issue by manudevcode** [dbramwell/react-animate-on-scroll#55]
I am trying to add landing page, but it does not work only if I configure the offset less than 50 I have tried it in different components and it does not work.
This is a fragment of my code: the FirstSection component is large but ScrollAnimation is not displayed when scrolling

PS. Sorry for my english.

```
  <ReactCSSTransitionGroup
    transitionName="section"
    transitionAppear={true}
    transitionAppearTimeout={500}
    transitionEnter={false}
    transitionLeave={false}>

    <FirstSection currentUser={currentUser}/>
    
    <ScrollAnimation animateIn="fadeInLeft">
      Hola
    </ScrollAnimation>

  </ReactCSSTransitionGroup>
```

**Comment by hudrdev** [comment]
Same issue :(

**Comment by Pixelycia** [comment]
Use the version of `animate.css:^3.7.2`

**Comment by ajj-siraj** [comment]
> Use the version of `animate.css:^3.7.2`

Doesn't work for me.

**Comment by IZUNA894** [comment]
same issue...not working at all ..i have tried many animate.css classes but none of them are working

**Comment by williamgravel** [comment]
As of [animate.css v4.0.0](https://github.com/animate-css/animate.css/releases/tag/v4.0.0), CSS classes for animations are all prefixed with `animate__` to avoid class clashes. Simply replace `animateIn="fadeInLeft"` with `animateIn="animate__fadeInLeft"` to fix this issue.

**Comment by nadrianai** [comment]
It's not working for me

**Comment by im-amir** [comment]
please import compat css instead of min
import "animate.css/animate.compat.css";

**Comment by manudevcode** [comment]
I deleted the folder and upgraded to the latest version and it worked.
