### ISSUE TITLE
Scroll not working: TypeError: Cannot read property 'pageYOffset' of null

### ISSUE THREAD

**Issue by tambatd** [dbramwell/react-animate-on-scroll#62]
**scrollableParentSelector not working**

when attempting to execute code as shown on your site's example of scrollableParentSelector
```
<ScrollAnimation animateIn='fadeIn'
  animateOut='fadeOut'
  scrollableParentSelector='#scrolly-div'>
  <h1>
    scrollableParentSelector
  </h1>
</ScrollAnimation>
```
  _**scrollableParentSelector='#scrolly-div'>**_ raises error 
TypeError: Cannot read property 'pageYOffset' of null

_ScrollAnimation.getScrollPos_
>138 | }, {
  139 |   key: "getScrollPos",
  140 |   value: function getScrollPos() {
 141 |     if (this.scrollableParent.pageYOffset !== undefined) {
 142 |       return this.scrollableParent.pageYOffset;
  143 |     }
  144 | 

unsure how to proceed, please advise

**Comment by dbramwell** [comment]
Hi

Might be a silly question, but are you using it within a scrollable div with the id "scrolly-div"? Eg:

```
<div id="scrolly-div" style="height: 300vh;">
<ScrollAnimation animateIn='fadeIn'
  animateOut='fadeOut'
  scrollableParentSelector='#scrolly-div'>
  <h1>
    scrollableParentSelector
  </h1>
</ScrollAnimation>
</div>
```

**Comment by tambatd** [comment]
> Hi
> 
> Might be a silly question, but are you using it within a scrollable div with the id "scrolly-div"? Eg:
> 
> ```
> <div id="scrolly-div" style="height: 300vh;">
> <ScrollAnimation animateIn='fadeIn'
>   animateOut='fadeOut'
>   scrollableParentSelector='#scrolly-div'>
>   <h1>
>     scrollableParentSelector
>   </h1>
> </ScrollAnimation>
> </div>
> ```

no, I have a react js block `{this.state.token &&(
              <ScrollAnimation animateIn='flipInY' animateOut='flipOutY' scrollableParentSelector='#root' className="SongBox">
               <div className="SongBox"> 
            <br></br>
            <h3>Check out these songs!</h3>
            <br></br>
              <iframe title="spotify player" src="https://open.spotify.com/embed/track/71twXgo4FGf0dP5Y3cXZ9b" width="300" height="80" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>
              <iframe title="spotify player" src="https://open.spotify.com/embed/track/1Ob98NWvtnKx4xP6QhRHmt" width="300" height="80" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>
              <iframe title="spotify player" src="https://open.spotify.com/embed/track/7pfOV26Wzr1KcV8rtIG2FU" width="300" height="80" frameBorder="0" allowtransparency="true" allow="encrypted-media"></iframe>
            <br></br>
            <br></br>
          </div>
          </ScrollAnimation>
                
          )}`

when replacing #root with #scrolly-div TypeError: Cannot read property 'pageYOffset' of null occurs

**Comment by dbramwell** [comment]
`#scrolly-div` needs to be replaced with a selector that points to whatever scrollable element contains you animation. The example above could just as easily be:
```
<div id="whatever" style="height: 300vh;">
<ScrollAnimation animateIn='fadeIn'
  animateOut='fadeOut'
  scrollableParentSelector='#whatever'>
  <h1>
    scrollableParentSelector
  </h1>
</ScrollAnimation>
</div>
```
What is the scrollable container of your ScrollAnimation?
