### ISSUE TITLE
Library not working with Server Side Rendering

### ISSUE THREAD

**Issue by Verurteilt** [dbramwell/react-animate-on-scroll#7]
Is there any chance you intend to support Server Side Rendering?

The error is simple:

`ReferenceError: Uncaught error: window is not defined at new ScrollAnimation`

**Comment by dbramwell** [comment]
Yeah I stumbled across this the other day while investigating a previous issue. I hadn't thought about it before, but I guess it's good to support as much as possible.

Your pull request fails all the travis ci tests though. I'm not familiar at all with how much of the javascript gets executed serverside, but if it gets into [isvisible()](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L74) then I guess you'll get issues as window.scrollY etc is not defined.

I'll do some more investigation when I get chance, but might not be till next week.

**Comment by Verurteilt** [comment]
Constructor, componentWillMount and render of course are the only methods in the life-cycle of a React  Component that get executed, I will give another shot to see if it passes the tests thou.

**Comment by Verurteilt** [comment]
@dbramwell  Done, the last Pull Request I sent passed all the tests, do you think you could merge it ASAP? We use your library in 3 web pages and we would be very happy if SSR would be supported in this library.

**Comment by Verurteilt** [comment]
NVM, it doesn't work as expected, after server side rendering animations on the browser don't work :/

**Comment by oyeanuj** [comment]
@Verurteilt @dbramwell Curious where did you folks end up with ideas on SSR support? 

I assume that this library would check for `window` and if it doesn't exist, skip the setup and would try it again on `componentDidMount` on the client?

**Comment by ernerock** [comment]
pending pull-request #12 that will disable any window events and remove clases and styles form the element if server-rendering. This will prevent it from breaking and work as usual when not server-rendered. Adjustments and suggestions are welcome

**Comment by dbramwell** [comment]
Nice work, thanks!

Was there a reason for doing this:
`
try {
  if (window && window.addEventListener) {
    window.removeEventListener("scroll", this.listener);
  }
}catch(e){
  console.log("error unmounting event listener:", e);
}
`
Over checking for state.serverSide ?

I'll try your code when I get chance (hopefully Thursday), merge and do a release.

**Comment by ernerock** [comment]
not really, it can be substituted with the state.serverSide condition. I just used that initially to try to find the breaking points. Feel free to change it. Thanks

**Comment by mmmaaatttttt** [comment]
Any updates on getting this merged? Just encountered this issue myself today, would love to see it fixed!

**Comment by dbramwell** [comment]
Thanks again for your work on this @ernerock 

I've left a comment on the markup section of the pull request. It gives me warnings with NextJS stating that client and serverside markup are different. If I change the markup back to how it was then this warning goes away and everything works great. If changing the markup back doesn't break your setup then I'm good to merge.

**Comment by ernerock** [comment]
Thanks @dbramwell 
Left a more detailed response in the PR but will follow up tomorrow.

**Comment by dbramwell** [comment]
Thanks for your work @ernerock. Merged and released version 1.4.0
