### ISSUE TITLE
Delayed function invocations (throttle) are not cleaned up upon ScrollAnimation unmount (tries to read property of null)

### ISSUE THREAD

**Issue by henriqueinonhe** [dbramwell/react-animate-on-scroll#76]
https://user-images.githubusercontent.com/20905415/231197036-5e0be7ce-1979-4e74-9c5f-8767f17b637d.mp4

Example's code:

```tsx
const DummyPage: NextPage = () => {
  const [show, setShow] = useState(true);

  return (
    <>
      <div style={{ position: "fixed", top: 0 }}>
        <button onClick={() => setTimeout(() => setShow((show) => !show), 1000)}>CLICK</button>
      </div>

      <div style={{ paddingTop: 1200, paddingBottom: 200 }}>
        {show && (
          <>
            <ScrollAnimation animateIn="fadeInUp">
              <div>FOO</div>
            </ScrollAnimation>
          </>
        )}
      </div>
    </>
  );
};
```

Even though we clear the timeouts we ourselves set, we're **not** clearing timeouts set by Lodash's throttle, thus causing an error whenever a ScrollAnimation unmounts while we still have delayed function invocations pending.

The fix is pretty simple, we just need to call de throttled function's cancel upon unmount, I'll be adding a PR.

**Comment by dbramwell** [comment]
Merged in #79 and released in v2.1.7
