### ISSUE TITLE
react@"^18.2.0" from the root project Could not resolve dependency: npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.7

### ISSUE THREAD

**Issue by EsinShadrach** [dbramwell/react-animate-on-scroll#82]
react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.7

doesn't install with react@"^18.2.0"

**Comment by mrepol742** [comment]
Try this
npm config set legacy-peer-deps true
npm i

**Comment by EsinShadrach** [comment]
Thanks!
